[versions]
aboutlib_version = "10.10.0"
coil_version = "2.6.0"
compose_compiler_version = "1.5.8"
coroutines_version = "1.8.0"
hilt_version = "2.50"
kotlin_version = "1.9.22"
ktor_version = "2.3.2"

[plugins]
android-application = { id = "com.android.application", version = "8.2.2" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin_version" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin_version" }
ksp = { id = "com.google.devtools.ksp", version = "1.9.22-1.0.17" }

kotlinter = { id = "org.jmailen.kotlinter", version = "4.1.0" }

[libraries]
aboutLibraries-gradle = { module = "com.mikepenz.aboutlibraries.plugin:aboutlibraries-plugin", version.ref = "aboutlib_version" }
aboutLibraries-compose = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutlib_version" }

androidx-core = "androidx.core:core-ktx:1.12.0"

coil-core = { module = "io.coil-kt:coil", version.ref = "coil_version" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil_version" }

compose-bom = { module = "dev.chrisbanes.compose:compose-bom", version = "2024.02.00-alpha02" }
compose-material = { module = "androidx.compose.material:material" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-ui-tooling-debug = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-util = { module = "androidx.compose.ui:ui-util" }
compose-activity = { module = "androidx.activity:activity-compose", version = "1.8.2" }
compose-lintchecks = { module = "com.slack.lint.compose:compose-lint-checks", version = "1.2.0" }

navigation-compose = "androidx.navigation:navigation-compose:2.7.7"
navigation-accompanist = "com.google.accompanist:accompanist-navigation-material:0.35.0-alpha"

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines_version" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines_version" }

desugar = { module = "com.android.tools:desugar_jdk_libs", version = "2.0.4" }

hilt-gradle = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt_version" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt_version" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt_version" }
hilt-navigation = "androidx.hilt:hilt-navigation-compose:1.2.0"

timber = "com.jakewharton.timber:timber:5.0.1"

ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor_version" }
ktor-logging = { module = "io.ktor:ktor-client-android", version.ref = "ktor_version" }

preferences-androidx = { module = "androidx.preference:preference-ktx", version = "1.2.1" }
preferences-flow = { module = "com.github.tfcporciuncula:flow-preferences", version = "1.4.0" }

serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.6.3" }

[bundles]
coil = ["coil-core", "coil-compose"]
compose = ["compose-activity", "compose-material", "compose-material-icons-extended", "compose-material3", "compose-ui", "compose-ui-tooling", "compose-ui-util"]
compose-debug = ["compose-ui-tooling-debug"]
coroutines = ["coroutines-core", "coroutines-android"]
ktor = ["ktor-core", "ktor-logging"]
navigation = ["navigation-compose", "navigation-accompanist", "hilt-navigation"]
preferences = ["preferences-androidx", "preferences-flow"]